GET http://localhost:4001/flights HTTP/1.1
content-type: application/json

###
GET http://localhost:4001/test HTTP/1.1
content-type: application/json


###
POST http://localhost:4001/flights HTTP/1.1
content-type: application/json

{
    "flightNumber": "AA1d23",
    "timeDepart": "08:00",
    "timeArrive": "10:00",
    "cityDepart": "New York",
    "cityArrive": "Chicago",
    "gate": "A4"
  }

###
PUT http://localhost:4001/flights/4 HTTP/1.1
content-type: application/json

{
    "flightNumber": "AA1d23",
    "timeDepart": "08:00",
    "timeArrive": "10:00",
    "cityDepart": "New York",
    "cityArrive": "Chicago",
    "gate": "A8"
  }
###
GET http://localhost:4001/flights/4 HTTP/1.1
content-type: application/json
###

DELETE http://localhost:4001/flights/4 HTTP/1.1
content-type: application/json
